# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('requirement', models.BooleanField(default=False)),
                ('needs_value', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'argument',
                'verbose_name_plural': 'arguments',
                'db_table': 'arguments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='command')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'command',
                'verbose_name_plural': 'commands',
                'db_table': 'commands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='source name')),
                ('version', models.CharField(max_length=100, verbose_name='version')),
                ('category', models.IntegerField(choices=[(1, 'Flow Sentences'), (2, 'OS'), (3, 'Product'), (4, 'Robot Framework'), (5, 'External Libraries')], verbose_name='category')),
                ('depends', models.ManyToManyField(blank=True, to='Products.Source')),
            ],
            options={
                'verbose_name': 'source',
                'verbose_name_plural': 'sources',
                'db_table': 'sources',
            },
        ),
        migrations.AddField(
            model_name='command',
            name='source',
            field=models.ManyToManyField(blank=True, to='Products.Source'),
        ),
        migrations.AddField(
            model_name='argument',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Command'),
        ),
        migrations.AddField(
            model_name='argument',
            name='exclude',
            field=models.ManyToManyField(blank=True, help_text='Choose parameters that should be excluded if this is set.', null=True, related_name='_argument_exclude_+', to='Products.Argument', verbose_name='exclude'),
        ),
        migrations.AddField(
            model_name='argument',
            name='include',
            field=models.ManyToManyField(blank=True, help_text='Choose mandatory parameters if this is set.', null=True, related_name='_argument_include_+', to='Products.Argument', verbose_name='include'),
        ),
    ]
