# Generated by Django 2.2.12 on 2020-07-16 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='source name')),
                ('version', models.CharField(max_length=100, verbose_name='version')),
                ('category', models.IntegerField(choices=[(1, 'Flow Sentences'), (2, 'OS'), (3, 'Product'), (4, 'Robot Framework'), (5, 'External Libraries')], verbose_name='category')),
                ('depends', models.ManyToManyField(blank=True, to='Products.Source')),
            ],
            options={
                'verbose_name': 'source',
                'verbose_name_plural': 'sources',
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='command')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('source', models.ManyToManyField(blank=True, to='Products.Source')),
            ],
            options={
                'verbose_name': 'command',
                'verbose_name_plural': 'commands',
                'db_table': 'commands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('requirement', models.BooleanField(default=False)),
                ('needs_value', models.BooleanField(default=False)),
                ('command', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.Command')),
                ('exclude', models.ManyToManyField(blank=True, help_text='Choose parameters that should be excluded if this is set.', related_name='_argument_exclude_+', to='Products.Argument', verbose_name='exclude')),
                ('include', models.ManyToManyField(blank=True, help_text='Choose mandatory parameters if this is set.', related_name='_argument_include_+', to='Products.Argument', verbose_name='include')),
            ],
            options={
                'verbose_name': 'argument',
                'verbose_name_plural': 'arguments',
                'db_table': 'arguments',
                'ordering': ['id'],
            },
        ),
    ]
