# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_control_flow_setences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=255, verbose_name='source name'),
        ),
        migrations.AlterField(
            model_name='source',
            name='version',
            field=models.CharField(max_length=100, verbose_name='version'),
        ),
    ]
