# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20170928_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='argument',
            options={'ordering': ['name'], 'verbose_name': 'argument', 'verbose_name_plural': 'arguments'},
        ),
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['name'], 'verbose_name': 'command', 'verbose_name_plural': 'commands'},
        ),
    ]
