# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20171010_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='argument',
            options={'ordering': ['id'], 'verbose_name': 'argument', 'verbose_name_plural': 'arguments'},
        ),
    ]
