apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: bluexolo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi