#!/bin/bash

today=$(date +%Y-%m-%d_%H:%M)
# ensuring that this sed script will work on
# any sed version. (includes macosx)
sed -i '' "/REFRESHED_AT/c\\
ENV REFRESHED_AT=$today"$'\n' Dockerfile
docker rm $(docker ps -qa)
docker rmi bluexolo
docker build -t bluexolo .
