#!/bin/bash

cd ..
zip docker/sources/bluexolo_src.zip\
 -x '/docker/*' \
 -x '/tools/*' \
 -x '/media/*' \
 -x '/logs/*' \
 -x '/.git/*' \
 -x '/.github/*' \
 -x '/.gitignore'  \
 -r .
 cd -
today=$(date +%Y-%m-%d_%H:%M)
# ensuring that this sed script will work on
# any sed version. (includes macosx)
sed -i '' "/REFRESHED_AT/c\\
ENV REFRESHED_AT=$today"$'\n' Dockerfile
docker rm $(docker ps -qa)
docker build -t bluexolo/bluexolo:latest .
docker rmi $(docker images|grep none|awk '{print $3}')
