# Generated by Django 2.2.12 on 2020-07-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('category', models.IntegerField(choices=[(1, 'Global Variables'), (2, 'Local Network Connection'), (3, 'Jenkins Connection')], default=1, verbose_name='category')),
                ('value_type', models.IntegerField(choices=[(1, 'String'), (2, 'List')], default=1, verbose_name='value type')),
            ],
            options={
                'verbose_name': 'parameter',
                'verbose_name_plural': 'parameters',
                'db_table': 'parameters',
            },
        ),
        migrations.CreateModel(
            name='ServerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('config', models.TextField(blank=True)),
                ('category', models.IntegerField(choices=[(1, 'Global Variables'), (2, 'Local Network Connection'), (3, 'Jenkins Connection')], default=1, verbose_name='category')),
            ],
            options={
                'verbose_name': 'server_profile',
                'verbose_name_plural': 'server_profiles',
                'db_table': 'servers_profiles',
            },
        ),
        migrations.CreateModel(
            name='TemplateServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.IntegerField(choices=[(1, 'Global Variables'), (2, 'Local Network Connection'), (3, 'Jenkins Connection')], default=1, verbose_name='category')),
                ('parameters', models.ManyToManyField(blank=True, to='Servers.Parameters')),
            ],
            options={
                'verbose_name': 'server_template',
                'verbose_name_plural': 'servers_templates',
                'db_table': 'servers_templates',
            },
        ),
    ]
