# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servers', '0004_auto_20171024_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='value_type',
            field=models.IntegerField(choices=[(1, 'String'), (2, 'List')], default=1, verbose_name='value type'),
        ),
    ]
