# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servers', '0005_auto_20171025_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
    ]
