# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_task_task_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.IntegerField(choices=[(1, 'Extract'), (2, 'Run Script')], default=2),
        ),
        migrations.AddField(
            model_name='task',
            name='task_result',
            field=models.TextField(blank=True),
        ),
    ]
