# Generated by Django 2.2.12 on 2020-07-16 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='Products.Source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'db_table': 'collections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Products.Source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'phase',
                'verbose_name_plural': 'phases',
                'db_table': 'phases',
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('script', models.TextField(blank=True, verbose_name='script')),
                ('values', models.TextField(blank=True, verbose_name='values')),
                ('extra_imports', models.TextField(blank=True, verbose_name='extra imports ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('script_type', models.PositiveIntegerField(choices=[(1, 'Native'), (2, 'Imported')], default=1, verbose_name='script type')),
                ('collection', models.ManyToManyField(to='Testings.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'test suite',
                'verbose_name_plural': 'test suites',
                'db_table': 'testsuites',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('script', models.TextField(blank=True, verbose_name='script')),
                ('functions', models.CharField(blank=True, max_length=100, verbose_name='functions')),
                ('values', models.TextField(blank=True, verbose_name='values')),
                ('extra_imports', models.TextField(blank=True, verbose_name='extra imports ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('script_type', models.PositiveIntegerField(choices=[(1, 'Native'), (2, 'Imported')], default=1, verbose_name='script type')),
                ('collection', models.ManyToManyField(to='Testings.Collection')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Testings.Phase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'test case',
                'verbose_name_plural': 'test cases',
                'db_table': 'testcases',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('script', models.TextField(verbose_name='script')),
                ('values', models.TextField(blank=True, verbose_name='values')),
                ('extra_imports', models.TextField(blank=True, verbose_name='extra imports ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('script_type', models.PositiveIntegerField(choices=[(1, 'Native'), (2, 'Imported')], default=1, verbose_name='script type')),
                ('collection', models.ManyToManyField(blank=True, to='Testings.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
                'db_table': 'keywords',
            },
        ),
    ]
