# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'db_table': 'collections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('script', models.TextField(verbose_name='script')),
                ('values', models.TextField(blank=True, verbose_name='values')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('script_type', models.PositiveIntegerField(choices=[(1, 'Native'), (2, 'Imported')], default=1, verbose_name='script type')),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'phase',
                'verbose_name_plural': 'phases',
                'db_table': 'phases',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('script', models.TextField(blank=True, verbose_name='script')),
                ('functions', models.CharField(blank=True, max_length=100, verbose_name='functions')),
                ('values', models.TextField(blank=True, verbose_name='values')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'test case',
                'verbose_name_plural': 'test cases',
                'db_table': 'testcases',
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('script', models.TextField(blank=True, verbose_name='script')),
                ('values', models.TextField(blank=True, verbose_name='values')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('collection', models.ManyToManyField(to='Testings.Collection')),
            ],
            options={
                'verbose_name': 'test suite',
                'verbose_name_plural': 'test suites',
                'db_table': 'testsuites',
            },
        ),
    ]
