# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_control_flow_setences'),
        ('Testings', '0002_keyword_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Products.Source')),
                ('robot_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Robot_Version', to='Products.Source')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'db_table': 'collections',
            },
        ),
    ]
