# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Testings', '0004_auto_20170925_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='Testings.Keyword'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Products.Source'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='robot_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_Version', to='Products.Source'),
        ),
    ]
