# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Testings', '0005_auto_20170926_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='robot_version',
        ),
        migrations.AlterField(
            model_name='collection',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Products.Source'),
        ),
    ]
