# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Testings', '0006_auto_20171006_0421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['name'], 'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Products.Source'),
        ),
    ]
