# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servers', '0002_FirstCustomTemplateServer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Testings', '0007_auto_20171017_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('script', models.TextField(verbose_name='script')),
                ('values', models.TextField(blank=True, verbose_name='values')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('collection', models.ManyToManyField(blank=True, to='Testings.Collection')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servers.ServerProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'testcase',
                'verbose_name_plural': 'testcases',
                'db_table': 'testcases',
            },
        ),
    ]
