# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Testings', '0008_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='collection',
            field=models.ManyToManyField(to='Testings.Collection'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Servers.ServerProfile'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='script',
            field=models.TextField(blank=True, verbose_name='script'),
        ),
    ]
