# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testings', '0009_auto_20171026_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='keywords',
        ),
        migrations.AddField(
            model_name='keyword',
            name='collection',
            field=models.ManyToManyField(blank=True, to='Testings.Collection'),
        ),
    ]
