# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20171017_1703'),
        ('Testings', '0010_auto_20171026_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Source')),
            ],
            options={
                'verbose_name': 'phase',
                'verbose_name_plural': 'phases',
                'db_table': 'phases',
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='functions',
            field=models.CharField(blank=True, max_length=100, verbose_name='functions'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='phase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Testings.Phase'),
            preserve_default=False,
        ),
    ]
