# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testings', '0011_auto_20171101_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='profile',
        ),
    ]
