# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testings', '0013_auto_20171108_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='script_type',
            field=models.PositiveIntegerField(choices=[(1, 'Native'), (2, 'Imported')], default=1, verbose_name='script type'),
        ),
    ]
