# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testings', '0014_keyword_script_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='extra_imports',
            field=models.TextField(blank=True, verbose_name='extra imports '),
        ),
        migrations.AddField(
            model_name='testcase',
            name='extra_imports',
            field=models.TextField(blank=True, verbose_name='extra imports '),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='extra_imports',
            field=models.TextField(blank=True, verbose_name='extra imports '),
        ),
    ]
