kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
metadata:
  namespace: bluexolo
resources:
  - "namespace.yaml"
  - "persistent-volume.yaml"
  - "persistent-volume-claim.yaml"
  - "config-maps.yaml"
  - "deployments.yaml"
  - "services.yaml"
  - "ingress.yaml"
  - "autoscaling.yaml"
secretGenerator:
  - name: "bluexolo-secrets"
    namespace: bluexolo
    envs:
    - ".k8.env" # Maybe this will be renamed as .env