apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  namespace: bluexolo
spec:
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/media"