apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
      containers:
      - name: django
        image: bluexolo/bluexolo:production
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: bluexolo-secrets
                key: DB_HOST
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bluexolo-secrets
                key: DB_PASSWORD
          - name: DJANGO_SU_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bluexolo-secrets
                key: DJANGO_SU_PASSWORD
          - name: EMAIL_HOST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bluexolo-secrets
                key: EMAIL_HOST_PASSWORD
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: bluexolo-secrets
                key: SECRET_KEY
        envFrom:
          - configMapRef: 
              name: django
        volumeMounts:
          - mountPath: "/var/www/media"
            name: media-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
      containers:
      - name: celery
        image: bluexolo/bluexolo:production
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        command: ["/bin/bash"]
        args: ["docker/celery-entrypoint.sh"]
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: bluexolo-secrets
                key: DB_HOST
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bluexolo-secrets
                key: DB_PASSWORD
          - name: DJANGO_SU_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bluexolo-secrets
                key: DJANGO_SU_PASSWORD
          - name: EMAIL_HOST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bluexolo-secrets
                key: EMAIL_HOST_PASSWORD
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: bluexolo-secrets
                key: SECRET_KEY
        envFrom:
          - configMapRef: 
              name: django
        volumeMounts:
          - mountPath: "/var/www/media"
            name: media-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
      containers:
      - name: nginx
        image: snvc00/bluexolo:proxyenvstatic
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: proxy
        volumeMounts:
          - mountPath: "/var/www/media"
            name: media-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2.1-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.6.21-alpine
        env:
          - name: POSTGRES_USER
            value: bluexolo
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bluexolo-secrets
                key: DB_PASSWORD
          - name: POSTGRES_DB
            value: bluexolo
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        args:
          - "-c"
          - "listen_addresses=*"
        ports:
          - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistant
spec:
  selector:
    matchLabels:
      app: assistant
  template:
    metadata:
      labels:
        app: assistant
    spec:
      containers:
      - name: assistant
        image: bluexolo/assistant
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: robot4-0
spec:
  selector:
    matchLabels:
      app: robot4-0
  template:
    metadata:
      labels:
        app: robot4-0
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: robot4-0
        image: bluexolo/robot:4.0
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 22